package com.example.wordsapp.lists

import com.example.wordsapp.objects.Animal

class Animals {

public val AnimalsList = listOf<Animal>(
    Animal(1, "Cóndor Andino","El cóndor andino, también cóndor de los Cerros, cóndor de los Andes, o simplemente cóndor  es una especie de ave de la familia Cathartidae que habita en América del Sur. El orden al que pertenece su familia se encuentra en disputa", "https://peru.info/Portals/0/Images/Productos/6/136-imagen-1457192582021.jpg", 1),
    Animal(2, "Pollo","El pollo es uno de los animales domésticos más comunes. Lo puedes encontrar en cualquier granja de tu zona. Se habla del pollo, desde hace miles de años, pero no exactamente del pollo, sino del macho de la especie: el gallo. El motivo de tanta fama, es solo uno: su típica costumbre de saludar al alba cantando.", "https://i.pinimg.com/originals/23/75/6a/23756ac9fa5b929623b104248b1ea74f.jpg", 1),
    Animal(3, "Ganso","Se llama comúnmente gansos u ocas a algunas aves de la subfamilia Anserinae, de la familia Anatidae, aunque también se denomina así a algunas aves de la subfamilia Tadorninae, así como a la especie Anseranas semipalmata, de la familia Anseranatidae. Familia Anatidae: Subfamilia Anserinae Género Anser", "https://e625.com/sitio/wp-content/uploads/2016/09/ganso.jpg", 1),
    Animal(4, "Pato","Pato es el nombre común para ciertas aves de la familia Anatidae, principalmente de la subfamilia Anatinae y dentro de ella del género Anas. No son un grupo monofilético, ya que no se incluyen los cisnes ni los gansos. Se incluyen bajo esta definición las siguientes especies: Subfamilia Anatinae", "https://cdn.pixabay.com/photo/2017/06/28/22/32/duck-2452431_960_720.jpg", 1),
    Animal(5, "Aguila","Águila es el nombre dado a las aves de presa, del orden de Accipitriformes, ,  familia Accipitridae, subfamilia Buteoninae. Pertenecen a varios géneros, los cuales están sujetos a una reclasificación más adecuada puesto que los expertos no llegan a una opinión consensuada", "https://estaticos.muyinteresante.es/uploads/images/article/5536592a70a1ae8d775df8a6/aves.jpg", 1),
    Animal(6, "Buitre","Los buitres son aves rapaces del orden Falconiformes que suelen alimentarse especialmente de animales muertos, aunque, a falta de estos, son capaces de cazar presas vivas. Los buitres se encuentran distribuidos por todos los continentes, excepto la Antártida y Oceanía.", "https://cdnuploads.aa.com.tr/uploads/Contents/2019/09/07/thumbs_b_c_8e7a41e278698c5fbf611aeba0df9f45.jpg?v=233427", 1),
    Animal(7, "Perro","El perro,  llamado perro doméstico o can,  y en algunos lugares coloquialmente llamado chucho,  tuso,  choco,  entre otros; es un mamífero carnívoro de la familia de los cánidos, que constituye una especie del género Canis.", "https://holatelcel.com/wp-content/uploads/2020/09/cheems-memes-9.jpg", 2),
    Animal(8, "Gato","El gato doméstico, llamado más comúnmente gato, y de forma coloquial minino,  michino,  michi,  micho,  mizo,  miz,  morroño o morrongo,  y algunos nombres más, es un mamífero carnívoro de la familia Felidae. Es una subespecie domesticada por la convivencia con el ser humano.", "https://c.tenor.com/Y4AzOUrW5GQAAAAS/gato-moviendo-la-cabeza-al-ritmo-de-la-musica.gif", 2),
    Animal(9, "Vaca","La vaca es un animal herbívoro que se alimenta principalmente del pasto, aunque también consume hierbas, tallos, hojas, semillas y raíces de numerosas plantas. Comen durante la mayor parte del día, en total, cerca de ocho horas diarias.", "https://storage.contextoganadero.com/s3fs-public/styles/noticias_one/public/ganaderia/field_image/2019-07/datos_curiosos.jpg?itok=K3YrNhVX", 2),
    Animal(10, "Oveja","La oveja es un mamífero cuadrúpedo ungulado doméstico, utilizado como ganado. Como todos los rumiantes, las ovejas son artiodáctilos, o animales con pezuñas. A pesar de que el término oveja se aplica a muchas especies del género Ovis, por lo general hace referencia a la subespecie doméstica de Ovis orientalis", "https://assets.adnradio.cl/2020/08/61a069aa7df4188b3e9c36009a1b013f-768x432.jpg", 2),
    Animal(11, "Caballo","El caballo  es un mamífero perisodáctilo domesticado de la familia de los équidos. Es un herbívoro perisodáctilo de gran porte, y cuello largo y arqueado poblado por largas crines. La mayoría de los animales que pastan tienen la pata hendida, es decir, sus patas terminan en dos dedos con casco.", "https://plantillasdememes.com/img/plantillas/juan-el-caballo01606539920.jpg", 2),
    Animal(12, "Sapo","Los bufónidos son una familia del orden Anura, un grupo de los anfibios conocidos. Muchas de sus especies se conocen con el nombre común de Vega; no obstante, numerosas especies pertenecientes a otras familias también son comúnmente denominados sapos.", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-YkcyJy2fmZ5qgNPY4K3PKzSwRa1wgvae4g&usqp=CAU", 3),
    Animal(13, "Salamandra","Los caudados, conocidos como salamandras y tritones, son un clado de anfibios compuesto por 695 especies vivas que se distribuyen en los continentes del hemisferio norte con la excepción de unas pocas especies en el norte de Sudamérica. Un tercio de las salamandras conocidas habitan en Norteamérica.", "https://pbs.twimg.com/media/Eu7rBRLWQAMXSOf.jpg", 3),
    Animal(14, "Tritón","Triturus es un género de anfibios caudados de la familia Salamandridae, compuesto por una serie de especies de Europa y Asia que se encuentran en cuerpos de agua, como estanques poco profundos, lagunas, arroyos y aguas profundas tranquilas; y terrestres, como páramos, pantanos y bosques.", "https://www.animales.website/wp-content/uploads/2018/05/Tritones.jpg", 3),
    Animal(15, "Cecilias","Los gimnofiones o Gymnophiona o cecilias son anfibios grandes sin patas, con forma de lombriz, principalmente de regiones tropicales húmedas, exhibiendo un estilo de vida fosorial al vivir bajo el suelo. Se encuentran en América, África, la India, Indochina y algunas otras regiones que formaron parte de Gondwana durante el Mesozoico. Los registros más antiguos de gimnofiones corresponden al holotipo de Eocaecilia micropodia del Jurásico Inferior", "https://www.nationalgeographic.com.es/medio/2020/07/06/siphonops-annulatus_31cc21d8_1200x630.jpg", 3),
    Animal(16, "Tiburones","Los selaquimorfos o selacimorfos son un superorden de condrictios conocidos comúnmente con el nombre de tiburones o escualos. Algunos grandes escualos, como el tiburón blanco y el toro, son conocidos a veces con el nombre de jaquetones", "https://www.nationalgeographic.com.es/medio/2018/02/27/tiburon__1280x720.jpg", 4),
    Animal(17, "Pez Payaso","Amphiprioninae es una subfamilia de peces marinos de la familia Pomacentridae, que engloba únicamente a los géneros Amphiprion y Premnas, cuyos componentes son conocidos como peces payaso o peces de las anémonas", "https://cdn1.intriper.com/wp-content/uploads/2019/12/19210342/payaso.jpg", 4),
    Animal(18, "Ballenas","En general, las ballenas son especies muy cosmopolitas, es decir que viven en prácticamente todos los océanos del mundo, y se alimentan principalmente de krill y pequeños crustáceos, como copépodos y anfípodos, aunque existen algunas diferencias entre las diferentes especies de ballenas.", "https://ichef.bbci.co.uk/news/640/cpsprodpb/2A3F/production/_95151801_mediaitem95151800.jpg", 4),
    Animal(19, "Delfines","Los delfines son cetáceos carnívoros y, también, son odontocetos, es decir, que tienen dientes. Se caracterizan por tener dos aletas laterales y una aleta triangular en su parte superior, junto con una cola horizontal que usan para impulsarse y un hocico en forma de pico.", "https://www.ngenespanol.com/wp-content/uploads/2018/08/%C2%BFC%C3%B3mo-escuchan-los-delfines.jpg", 4),
    Animal(20, "Pez Espada","El pez espada o aguja palá  es una especie de pez perciforme de la familia Xiphiidae. Son grandes peces predadores altamente migratorios, caracterizados por su pico largo y aplanado, diferente del de sus parientes, los marlines, que es cónico. ", "https://mejorconsalud.as.com/wp-content/uploads/2021/08/pez-espada.jpg", 4),
    Animal(21, "Lagarto","Los lacertilios o lagartos son un grupo parafilético de escamosos que incluye la mayoría de los escamosos actuales, como varanos, iguanas, coritofánidos, camaleones, lagartijas y geckos, así como algunas formas fósiles muy notables, como los mosasaurios del Cretácico Superior. ", "https://e00-elmundo.uecdn.es/elmundo/imagenes/2013/02/19/ciencia/1361269262_0.jpg", 5),
    Animal(22, "Culebra","Las culebras se caracterizan por tener la cabeza recubierta de escamas grandes de disposición típica. Las escamas dorsales y laterales del cuerpo son de contorno aproximadamente romboidal; en la parte ventral presentan una sola fila de escamas ensanchadas.", "https://www.informacionsobreanimales.com/wp-content/uploads/2019/01/Informaci%C3%B3n-sobre-la-serpiente-feroz-01.jpg", 5),
    Animal(23, "Iguana","La iguana es un reptil de la familia Iguanidae que se encuentra en América Latina y el Caribe. Habita sobre todo en bosques húmedos, donde prefiere vivir en los árboles, ya que es una excelente trepadora. Es un animal ovíparo, es decir, se reproduce por medio de huevos", "https://www.meme-arsenal.com/memes/df13e0e16c25999a48c16d5ef8fe5af9.jpg", 5),
    Animal(24, "Lagartija","La lagartijas más comunes suelen habitar en terrenos rocosos o pedregosos que reciban la luz solar durante varias horas. Esto es así, ya que tiene la posibilidad de acceder a rincones y huecos para esconderse de sus numerosos depredadores.", "https://laverdadnoticias.com/__export/1592922444924/sites/laverdad/img/2020/06/23/lagartijas_datos_curiosos_de_la_especie.jpg_1902800913.jpg", 5),
)

}